### ISSUE TITLE
Ohai::Exceptions::AttributeNotFound on first run

### ISSUE THREAD

**Issue by bradenwright** [miketheman/nginx#408]
On the first run there is an issue with:

```
ohai 'reload_nginx' do
  plugin 'nginx'
  action :nothing
end
```

Error:
```
* ohai[reload_nginx] action reload[2016-05-23T17:44:53+00:00] ERROR: Encountered error while running plugins: #<Ohai::Exceptions::AttributeNotFound: No such attribute: 'nginx'>
       
           
           ================================================================================
           Error executing action `reload` on resource 'ohai[reload_nginx]'
           ================================================================================
           
           Ohai::Exceptions::AttributeNotFound
           -----------------------------------
           No such attribute: 'nginx'
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb
           
            22: ohai "reload_nginx" do
            23:   action :nothing
            24:   plugin "nginx"
            25: end
            26: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb:22:in `from_file'
           
           ohai("reload_nginx") do
             action [:nothing]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             plugin "nginx"
             declared_type :ohai
             cookbook_name "nginx"
             recipe_name "ohai_plugin"
           end
           
           Platform:
           ---------
           x86_64-linux
           
       
       Running handlers:
       [2016-05-23T17:44:53+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-05-23T17:44:53+00:00] ERROR: Exception handlers complete
```

Running using Test-Kitchen(1.6.0)/Chef-Zero(12.10.24).

Everything works fine on the 2nd run, but this is obviously not ideal.  E.g. jenkins job to test our cookbooks will fail if it won't work on a clean run. 

It was previously working about a week ago or so, I don't think much/if anything has changed in my setup.  Any help would be much appreciated!!!

**Comment by bradenwright** [comment]
FYI... error comes from:

include_recipe 'nginx'

**Comment by bradenwright** [comment]
My apologies, I was on an old version.  I pinned to 2.7.6 and its working

**Comment by SwatiSuwalka** [comment]
Did you move to 2.7.6 version of nginx cookbook??
